esphome:
  min_version: 2024.11.0

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

ota:
  - platform: esphome

api:
  encryption:
    key: "mocOMfV36AcFQutGzL8zFiKH/CjtBWSGaudWSZm8D/M="

binary_sensor:
  - platform: status
    name: Status

sensor:
  - id: wifi_signal_db
    name: WiFi Signal
    platform: wifi_signal
    update_interval: 60s
    entity_category: diagnostic

  - id: wifi_signal_strength
    name: WiFi Strength
    platform: copy
    source_id: wifi_signal_db
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
  - platform: homeassistant
    id: growatt_battery_soc
    entity_id: sensor.growatt_battery_soc
    internal: true

  - id: growatt_battery_soc_percent
    name: Growatt Battery SOC
    platform: copy
    source_id: growatt_battery_soc
    filters:
      - lambda: return x;
    unit_of_measurement: "%"
    entity_category: diagnostic
    on_value:
      then:
        - lvgl.label.update: 
            id: energy_battery_label
            text:
                format: "Battery SOC: %f %%"
                args: [ 'id(growatt_battery_soc_percent).state' ]
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: diagnostic
    ssid:
      name: Connected SSID
      entity_category: diagnostic
    mac_address:
      name: Mac Address
      entity_category: diagnostic
